// angular/calculadora.component.ts
import { Component } from '@angular/core';

interface Alumno {
  nombre: string;
  practica: number | null;
  problemas: number | null;
  teorica: number | null;
}

interface Resultado {
  nombre: string;
  notaFinal: number;
}

@Component({
  selector: 'app-calculadora',
  templateUrl: './calculadora.component.html',
  styleUrls: ['./calculadora.component.css']
})
export class CalculadoraComponent {
  alumno: Alumno = {
    nombre: '',
    practica: null,
    problemas: null,
    teorica: null
  };
  resultado: Resultado | null = null;
  error: string | null = null;
  alumnosCalculados: Resultado[] = [];

  calcularCalificacion() {
    if (!this.alumno.nombre) {
      this.resultado = null;
      this.error = null;
      if (this.alumnosCalculados.length > 0) {
        console.log('Calificaciones Calculadas:', this.alumnosCalculados);
      }
      this.alumno = { nombre: '', practica: null, problemas: null, teorica: null };
      return;
    }

    if (this.alumno.practica === null || this.alumno.problemas === null || this.alumno.teorica === null ||
        this.alumno.practica < 0 || this.alumno.practica > 10 ||
        this.alumno.problemas < 0 || this.alumno.problemas > 10 ||
        this.alumno.teorica < 0 || this.alumno.teorica > 10) {
      this.resultado = null;
      this.error = 'Error: Las notas deben estar entre 0 y 10.';
      return;
    }

    const notaFinal = (this.alumno.practica * 0.10) + (this.alumno.problemas * 0.50) + (this.alumno.teorica * 0.40);
    this.resultado = { nombre: this.alumno.nombre, notaFinal: notaFinal };
    this.error = null;
    this.alumnosCalculados.push(this.resultado);

    // Limpiar el formulario para el siguiente alumno
    this.alumno = { nombre: '', practica: null, problemas: null, teorica: null };
  }
}

<h2>Calculadora de Calificaciones</h2>
<form (ngSubmit)="calcularCalificacion()">
  <div>
    <label for="nombre">Nombre del Alumno:</label>
    <input type="text" id="nombre" name="nombre" [(ngModel)]="alumno.nombre" required>
  </div>
  <div>
    <label for="practica">Nota Práctica (0-10):</label>
    <input type="number" id="practica" name="practica" [(ngModel)]="alumno.practica" min="0" max="10" required>
  </div>
  <div>
    <label for="problemas">Nota Problemas (0-10):</label>
    <input type="number" id="problemas" name="problemas" [(ngModel)]="alumno.problemas" min="0" max="10" required>
  </div>
  <div>
    <label for="teorica">Nota Teórica (0-10):</label>
    <input type="number" id="teorica" name="teorica" [(ngModel)]="alumno.teorica" min="0" max="10" required>
  </div>
  <button type="submit">Calcular Calificación</button>
</form>

<div *ngIf="resultado" class="resultado">
  <h3>Resultado:</h3>
  <p>{{ resultado.nombre }} - Nota Final: {{ resultado.notaFinal | number:'1.2-2' }}</p>
</div>

<div *ngIf="error" class="error">
  <p>{{ error }}</p>
</div>

// react/Calculadora.js
import React, { useState } from 'react';
import './Calculadora.css';

function Calculadora() {
  const [nombre, setNombre] = useState('');
  const [practica, setPractica] = useState('');
  const [problemas, setProblemas] = useState('');
  const [teorica, setTeorica] = useState('');
  const [resultado, setResultado] = useState(null);
  const [error, setError] = useState(null);
  const [alumnosCalculados, setAlumnosCalculados] = useState([]);

  const calcularCalificacion = (event) => {
    event.preventDefault();

    if (nombre === '') {
      if (alumnosCalculados.length > 0) {
        console.log('Calificaciones Calculadas:', alumnosCalculados);
      }
      setNombre('');
      setPractica('');
      setProblemas('');
      setTeorica('');
      setResultado(null);
      setError(null);
      return;
    }

    const practicaNum = parseFloat(practica);
    const problemasNum = parseFloat(problemas);
    const teoricaNum = parseFloat(teorica);

    if (
      isNaN(practicaNum) || isNaN(problemasNum) || isNaN(teoricaNum) ||
      practicaNum < 0 || practicaNum > 10 ||
      problemasNum < 0 || problemasNum > 10 ||
      teoricaNum < 0 || teoricaNum > 10
    ) {
      setResultado(null);
      setError('Error: Las notas deben estar entre 0 y 10.');
      return;
    }

    const notaFinal = (practicaNum * 0.10) + (problemasNum * 0.50) + (teoricaNum * 0.40);
    const nuevoResultado = { nombre, notaFinal: notaFinal.toFixed(2) };
    setResultado(nuevoResultado);
    setError(null);
    setAlumnosCalculados([...alumnosCalculados, nuevoResultado]);

    // Limpiar el formulario para el siguiente alumno
    setNombre('');
    setPractica('');
    setProblemas('');
    setTeorica('');
  };

  return (
    <div className="container">
      <h2>Calculadora de Calificaciones</h2>
      <form onSubmit={calcularCalificacion}>
        <div>
          <label htmlFor="nombre">Nombre del Alumno:</label>
          <input
            type="text"
            id="nombre"
            value={nombre}
            onChange={(e) => setNombre(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="practica">Nota Práctica (0-10):</label>
          <input
            type="number"
            id="practica"
            min="0"
            max="10"
            value={practica}
            onChange={(e) => setPractica(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="problemas">Nota Problemas (0-10):</label>
          <input
            type="number"
            id="problemas"
            min="0"
            max="10"
            value={problemas}
            onChange={(e) => setProblemas(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="teorica">Nota Teórica (0-10):</label>
          <input
            type="number"
            id="teorica"
            min="0"
            max="10"
            value={teorica}
            onChange={(e) => setTeorica(e.target.value)}
          />
        </div>
        <button type="submit">Calcular Calificación</button>
      </form>

      {resultado && (
        <div className="resultado">
          <h3>Resultado:</h3>
          <p>{resultado.nombre} - Nota Final: {resultado.notaFinal}</p>
        </div>
      )}

      {error && (
        <div className="error">
          <p>{error}</p>
        </div>
      )}
    </div>
  );
}

export default Calculadora;
